name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve AgentFlow's documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - README
        - API Documentation
        - Tutorial/Guide
        - Adapter Documentation
        - Code Comments
        - Examples
        - Contributing Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's unclear or missing?
      description: Describe what documentation is unclear, incorrect, or missing
      placeholder: The documentation for X doesn't explain...
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: It would be clearer if...
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: File/Section Location
      description: Which file or section needs improvement?
      placeholder: "e.g., README.md line 45, docs/CLAUDE_ADAPTER.md"

  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to improve this documentation
          required: false
