name: Feature Request
description: Suggest an idea for AgentFlow
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: dropdown
    id: component
    attributes:
      label: Which component does this relate to?
      options:
        - CLI
        - Adapters
        - Viewer
        - Configuration
        - Testing
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        I need this feature because...
        It would help me to...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples, mockups, or code snippets if applicable
      render: python
      placeholder: |
        # Example usage:
        agentflow --new-feature ...

  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR to implement this feature
          required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with AgentFlow's goals
          required: true
